### ISSUE TITLE
Set first day

### ISSUE THREAD

**Issue by javiSwift** [graycampbell/GCCalendar#27] opened 2017-04-10 08:31 UTC
Hi,

Would be possible to set the first day of the calendar as an option?

Thanks😜

**Comment by graycampbell** [comment] 2017-04-10 20:07
Just to make sure I understand exactly what you mean, do you mean set the date range of the calendar (the bounds, in other words)? As in, only have the calendar display dates within a certain range or after a certain date?

Or do you mean setting the first selected day of the calendar (i.e. some date other than "today")?

**Comment by smhk** [comment] 2017-04-10 21:23
purely FYI in case he doesn't get back, I believe Javi just meant, like, "first day of the week" (ie week starts on either monday or sunday)...

**Comment by javiSwift** [comment] 2017-04-10 21:25
Effectively it's the first day of the week as I've seen this calendar always starts on Sunday.

Regards.

**Comment by graycampbell** [comment] 2017-04-10 21:40
If you're referring to regions where the first day of the week is supposed to be something other than Sunday, then #26 fixes that problem, and the newest version of the calendar ([Version 2.1.1](https://github.com/graycampbell/GCCalendar/releases/tag/2.1.1)) should work properly with regions where Sunday is not the first day of the week by displaying the days of the week in the correct order. So all you would have to do is just make sure you're using the latest version.

If that answers your question, please let me know, and I'll close this issue.

**Comment by graycampbell** [comment] 2017-04-21 23:01
I'm going to mark this issue as a duplicate of #24 until I get confirmation that I can close it from @javiSwift.

**Comment by graycampbell** [comment] 2017-09-23 01:33
#32

**Closed by graycampbell** 2017-09-23 01:33 UTC
Labels: duplicate
