### ISSUE TITLE
To show selected month title without selecting 1st day of the month

### ISSUE THREAD

**Issue by ranudhurandar** [graycampbell/GCCalendar#40] opened 2018-07-17 09:12 UTC

**Comment by graycampbell** [comment] 2018-11-21 21:53
This wouldn't be as easy to implement as you might expect, so I'm not sure if or when this could be added, but I'll keep it in mind.

**Comment by graycampbell** [comment] 2018-11-21 21:55
Actually, this is a duplicate of #23, so I'm going to mark it as such and close this issue.

**Closed by graycampbell** 2018-11-21 21:55 UTC
Labels: enhancement, low priority
